import {
  GATE_CATEGORY_ARITHMETIC,
  GATE_TYPE_DEMUX2,
  GATE_TYPE_MUX2,
  GATE_TYPE_MUX4,
  GATE_TYPE_MUX8,
  PINC1,
  PINC2,
  PINC3,
  PINC6,
  PINC11,
} from "../../constants";
import { evalDemux2, evalMux2, evalMux4, evalMux8 } from "../../logic";
import type { ComponentDefinition } from "../../types";
import { cb } from "../helpers";

export const Muxes: ComponentDefinition[] = [
  cb({
    type: GATE_TYPE_MUX2,
    label: "",
    category: GATE_CATEGORY_ARITHMETIC,
    inputs: PINC3,
    outputs: PINC1,
    width: 80,
    height: 70,
    symbol: "M",
    inputLabels: ["D0", "D1", "S"],
    outputLabels: ["Y"],
    evaluate: evalMux2,
  }),
  cb({
    type: GATE_TYPE_MUX4,
    label: "",
    category: GATE_CATEGORY_ARITHMETIC,
    inputs: PINC6,
    outputs: PINC1,
    width: 80,
    height: 90,
    symbol: "M4",
    inputLabels: ["D0", "D1", "D2", "D3", "S0", "S1"],
    outputLabels: ["Y"],
    evaluate: evalMux4,
  }),
  cb({
    type: GATE_TYPE_MUX8,
    label: "",
    category: GATE_CATEGORY_ARITHMETIC,
    inputs: PINC11,
    outputs: PINC1,
    width: 80,
    height: 160,
    symbol: "M8",
    inputLabels: [
      "D0",
      "D1",
      "D2",
      "D3",
      "D4",
      "D5",
      "D6",
      "D7",
      "S0",
      "S1",
      "S2",
    ],
    outputLabels: ["Y"],
    evaluate: evalMux8,
  }),
  cb({
    type: GATE_TYPE_DEMUX2,
    label: "",
    category: GATE_CATEGORY_ARITHMETIC,
    inputs: PINC2,
    outputs: PINC2,
    width: 80,
    height: 60,
    symbol: "DM",
    inputLabels: ["D", "S"],
    outputLabels: ["Y0", "Y1"],
    evaluate: evalDemux2,
  }),
];

export default Muxes;
