/**
 * OR gate family: 2-input, 3-input, 4-input, 8-input, 16-input.
 */
import {
  GATE_CATEGORY_LOGIC,
  GATE_TYPE_OR,
  GATE_TYPE_OR3,
  GATE_TYPE_OR4,
  GATE_TYPE_OR8,
  GATE_TYPE_OR16,
  PINC1,
  PINC2,
  PINC3,
  PINC4,
  PINC8,
  PINC16,
} from "../../constants";
import { evalGateOr } from "../../logic";
import type { ComponentDefinition } from "../../types";
import { cb } from "../helpers";

export const OrGates: ComponentDefinition[] = [
  cb({
    type: GATE_TYPE_OR,
    label: "",
    category: GATE_CATEGORY_LOGIC,
    inputs: PINC2,
    outputs: PINC1,
    width: 60,
    height: 60,
    symbol: "≥1",
    inputLabels: ["A", "B"],
    outputLabels: ["Y"],
    evaluate: evalGateOr,
  }),
  cb({
    type: GATE_TYPE_OR3,
    label: "",
    category: GATE_CATEGORY_LOGIC,
    inputs: PINC3,
    outputs: PINC1,
    width: 60,
    height: 70,
    symbol: "≥1·3",
    inputLabels: ["A", "B", "C"],
    outputLabels: ["Y"],
    evaluate: evalGateOr,
  }),
  cb({
    type: GATE_TYPE_OR4,
    label: "",
    category: GATE_CATEGORY_LOGIC,
    inputs: PINC4,
    outputs: PINC1,
    width: 60,
    height: 80,
    symbol: "≥1·4",
    inputLabels: ["A", "B", "C", "D"],
    outputLabels: ["Y"],
    evaluate: evalGateOr,
  }),
  cb({
    type: GATE_TYPE_OR8,
    label: "",
    category: GATE_CATEGORY_LOGIC,
    inputs: PINC8,
    outputs: PINC1,
    width: 60,
    height: 120,
    symbol: "≥1·8",
    inputLabels: ["A", "B", "C", "D", "E", "F", "G", "H"],
    outputLabels: ["Y"],
    evaluate: evalGateOr,
  }),
  cb({
    type: GATE_TYPE_OR16,
    label: "",
    category: GATE_CATEGORY_LOGIC,
    inputs: PINC16,
    outputs: PINC1,
    width: 60,
    height: 200,
    symbol: "≥1·16",
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "A9",
      "A10",
      "A11",
      "A12",
      "A13",
      "A14",
      "A15",
    ],
    outputLabels: ["Y"],
    evaluate: evalGateOr,
  }),
];

export default OrGates;
