/**
 * Bus-wide logic gates: AND, OR, NOT in 4/8/16-bit variants.
 */
import {
  GATE_CATEGORY_BUS,
  GATE_TYPE_BUS_AND4,
  GATE_TYPE_BUS_AND8,
  GATE_TYPE_BUS_AND16,
  GATE_TYPE_BUS_NOT4,
  GATE_TYPE_BUS_NOT8,
  GATE_TYPE_BUS_NOT16,
  GATE_TYPE_BUS_OR4,
  GATE_TYPE_BUS_OR8,
  GATE_TYPE_BUS_OR16,
  PINC4,
  PINC8,
  PINC16,
} from "../../constants";
import { evalBusAnd, evalBusNot, evalBusOr } from "../../logic";
import type { ComponentDefinition } from "../../types";
import { cb } from "../helpers";

export const BusLogicGates: ComponentDefinition[] = [
  // Bus AND
  cb({
    type: GATE_TYPE_BUS_AND4,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC8,
    outputs: PINC4,
    width: 80,
    height: 110,
    symbol: "&4",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: ["A0", "A1", "A2", "A3", "B0", "B1", "B2", "B3"],
    outputLabels: ["Y0", "Y1", "Y2", "Y3"],
    evaluate: evalBusAnd,
  }),
  cb({
    type: GATE_TYPE_BUS_AND8,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC16,
    outputs: PINC8,
    width: 80,
    height: 200,
    symbol: "&8",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "B0",
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
    ],
    outputLabels: ["Y0", "Y1", "Y2", "Y3", "Y4", "Y5", "Y6", "Y7"],
    evaluate: evalBusAnd,
  }),
  cb({
    type: GATE_TYPE_BUS_AND16,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: 32,
    outputs: PINC16,
    width: 80,
    height: 200,
    symbol: "&16",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "A9",
      "A10",
      "A11",
      "A12",
      "A13",
      "A14",
      "A15",
      "B0",
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
      "B8",
      "B9",
      "B10",
      "B11",
      "B12",
      "B13",
      "B14",
      "B15",
    ],
    outputLabels: [
      "Y0",
      "Y1",
      "Y2",
      "Y3",
      "Y4",
      "Y5",
      "Y6",
      "Y7",
      "Y8",
      "Y9",
      "Y10",
      "Y11",
      "Y12",
      "Y13",
      "Y14",
      "Y15",
    ],
    evaluate: evalBusAnd,
  }),
  // Bus OR
  cb({
    type: GATE_TYPE_BUS_OR4,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC8,
    outputs: PINC4,
    width: 80,
    height: 110,
    symbol: "≥4",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: ["A0", "A1", "A2", "A3", "B0", "B1", "B2", "B3"],
    outputLabels: ["Y0", "Y1", "Y2", "Y3"],
    evaluate: evalBusOr,
  }),
  cb({
    type: GATE_TYPE_BUS_OR8,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC16,
    outputs: PINC8,
    width: 80,
    height: 200,
    symbol: "≥8",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "B0",
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
    ],
    outputLabels: ["Y0", "Y1", "Y2", "Y3", "Y4", "Y5", "Y6", "Y7"],
    evaluate: evalBusOr,
  }),
  cb({
    type: GATE_TYPE_BUS_OR16,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: 32,
    outputs: PINC16,
    width: 80,
    height: 200,
    symbol: "≥16",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "A9",
      "A10",
      "A11",
      "A12",
      "A13",
      "A14",
      "A15",
      "B0",
      "B1",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
      "B8",
      "B9",
      "B10",
      "B11",
      "B12",
      "B13",
      "B14",
      "B15",
    ],
    outputLabels: [
      "Y0",
      "Y1",
      "Y2",
      "Y3",
      "Y4",
      "Y5",
      "Y6",
      "Y7",
      "Y8",
      "Y9",
      "Y10",
      "Y11",
      "Y12",
      "Y13",
      "Y14",
      "Y15",
    ],
    evaluate: evalBusOr,
  }),
  // Bus NOT
  cb({
    type: GATE_TYPE_BUS_NOT4,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC4,
    outputs: PINC4,
    width: 80,
    height: 80,
    symbol: "!4",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: ["A0", "A1", "A2", "A3"],
    outputLabels: ["Y0", "Y1", "Y2", "Y3"],
    evaluate: evalBusNot,
  }),
  cb({
    type: GATE_TYPE_BUS_NOT8,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC8,
    outputs: PINC8,
    width: 80,
    height: 110,
    symbol: "!8",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7"],
    outputLabels: ["Y0", "Y1", "Y2", "Y3", "Y4", "Y5", "Y6", "Y7"],
    evaluate: evalBusNot,
  }),
  cb({
    type: GATE_TYPE_BUS_NOT16,
    label: "",
    category: GATE_CATEGORY_BUS,
    inputs: PINC16,
    outputs: PINC16,
    width: 80,
    height: 200,
    symbol: "!16",
    isBusInput: true,
    isBusOutput: true,
    inputLabels: [
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "A9",
      "A10",
      "A11",
      "A12",
      "A13",
      "A14",
      "A15",
    ],
    outputLabels: [
      "Y0",
      "Y1",
      "Y2",
      "Y3",
      "Y4",
      "Y5",
      "Y6",
      "Y7",
      "Y8",
      "Y9",
      "Y10",
      "Y11",
      "Y12",
      "Y13",
      "Y14",
      "Y15",
    ],
    evaluate: evalBusNot,
  }),
];

export default BusLogicGates;
